In [2]:
import numpy as np

In [99]:
# 버전확인
np.__version__

'1.19.2'

### 배열 자료구조 클래스인 ndarry - vector, matrix
### 배열의 차원과 크기  - ndim, shpae

In [100]:
def aryInfo(arr) :
    print('type : {}'.format(type(arr)))
    print('shape : {}, dimension : {}, dtype : {}'.format(arr.shape, arr.ndim, arr.dtype))
    print("Array's Data : \n", arr)

### 1차원 배열 만들기

In [102]:
ary = np.array([0,1,2,3,4,5,6,7,8,9])
print(ary)

# 동일한 결과 출력
ary = np.arange(0,10,1)
print(ary)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [103]:
aryInfo(ary)

type : <class 'numpy.ndarray'>
shape : (10,), dimension : 1, dtype : int32
Array's Data : 
 [0 1 2 3 4 5 6 7 8 9]


### Vectorized operation (벡터화 연산)

In [7]:
# 일반적인 연산결과가 아님
data = [0,1,2,3,4,5,6,7,8,9]
data * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [107]:
# for
answer = []
for d in data :
    answer.append(d*2)
print(answer,type(answer))

[2, 4, 6, 8, 10, 12, 14, 16, 18] <class 'list'>


In [106]:
# list comprehension
data2 = [d*2 for d in data]
print(data2, type(data2))

[2, 4, 6, 8, 10, 12, 14, 16, 18] <class 'list'>


In [109]:
# for / list comprehension 사용하지 않고 빠르게 연산수행 -> type : list
# type : ndarray
x = np.array(data)
x * 2
aryInfo(x)

type : <class 'numpy.ndarray'>
shape : (9,), dimension : 1, dtype : int32
Array's Data : 
 [1 2 3 4 5 6 7 8 9]


### 비교연산, 논리연산

In [122]:
oneAry = np.array([1,2,3])
twoAry = np.array([10,20,30])
# 괄호로 묶어도 결과 달라지지 않음 / 왜?
print(oneAry + twoAry *2)
print(oneAry + (twoAry*2))
print(2 * twoAry + oneAry)

[21 42 63]
[21 42 63]
[21 42 63]


In [12]:
oneAry == 2

array([False,  True, False])

In [13]:
twoAry > 10

array([False,  True,  True])

In [14]:
(oneAry == 2) & (twoAry > 10)

array([False,  True, False])

### 2차원 배열(행렬, matrix)

In [115]:
matrix = np.array([[0,1,2],[3,4,5]])
aryInfo(matrix)

type : <class 'numpy.ndarray'>
shape : (2, 3), dimension : 2, dtype : int32
Array's Data : 
 [[0 1 2]
 [3 4 5]]


In [116]:
print('행의 갯수 : ',len(matrix))
print('열의 갯수 : ',len(matrix[1]))

행의 갯수 :  2
열의 갯수 :  3


### 3차원 배열

In [17]:
threeDimAry = np.array([[[1,2,3,4],
                        [5,6,7,8],
                        [9,10,11,12]],
                       [[11,12,13,14],
                       [15,16,17,18],
                       [19,20,21,22]]])

In [18]:
aryInfo(threeDimAry)

type : <class 'numpy.ndarray'>
shape : (2, 3, 4), dimension : 3, dtype : int32
Array's Data : 
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]]


In [19]:
# 깊이 : 2, 행 : 3, 열 : 4
print(len(threeDimAry),len(threeDimAry[0]),len(threeDimAry[0][0]))

2 3 4


In [123]:
# type : U11 - 문자형
x = np.array([100,'hello',3.14])
print('array {}'.format(x))
print('type {}'.format(type(x)))
print('x.dtype {}'.format(x.dtype))
print('x[0] type {}'.format(type(x[0])))

array ['100' 'hello' '3.14']
type <class 'numpy.ndarray'>
x.dtype <U11
x[0] type <class 'numpy.str_'>
100


In [21]:
# ndim : 배열의 차원
# shape : 배열의 크기
data = np.array([0,1,2,3,4,5])
aryInfo(data)

type : <class 'numpy.ndarray'>
shape : (6,), dimension : 1, dtype : int32
Array's Data : 
 [0 1 2 3 4 5]


In [22]:
data[2]

2

In [23]:
data[-1]

5

In [24]:
matrix = np.array([[0,1,2],[3,4,5]])
aryInfo(matrix)

type : <class 'numpy.ndarray'>
shape : (2, 3), dimension : 2, dtype : int32
Array's Data : 
 [[0 1 2]
 [3 4 5]]


In [25]:
print(matrix[1][1])
print(matrix[1,1])

4
4


In [26]:
print(matrix[-1,-1])
print(matrix[-1,-3])

5
3


- 슬라이싱
- 첫번째 행의 전체
- 두번째 열의 전체
- 두번째 행의 두번째 열부터 끝열까지

In [28]:
print(matrix[0:1])
print(matrix[:,1]) 
print(matrix[1,1:]) 

[[0 1 2]]
[1 4]
[4 5]


In [125]:
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

In [130]:
# 값 7을 인덱싱하라
print(m[1,2])
# 값 14를 인덱싱하라
print(m[-1,-1])
# 배열 [6,7]을 슬라이싱하라
print(m[1,1:3])
# 배열 [7,12]을 슬라이싱하라
print(m[1:,2])
# 배열 [[3,4],[8,9]]를 슬라이싱하라
print(m[:2,-2:])
print(m[:2,3:])

7
14
[6 7]
[ 7 12]
[[3 4]
 [8 9]]
[[3 4]
 [8 9]]


In [31]:
# boolean indexing
odd_even = np.array([0,1,2,3,4,5,6,7,8,9])
idx = np.array([True,False,True,False,True,False,True,False,True,False])
aryInfo(odd_even)

type : <class 'numpy.ndarray'>
shape : (10,), dimension : 1, dtype : int32
Array's Data : 
 [0 1 2 3 4 5 6 7 8 9]


In [32]:
# true만 출력
odd_even[idx]

array([0, 2, 4, 6, 8])

In [33]:
# return : bool
odd_even % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [34]:
# return : value
odd_even[odd_even % 2 == 0]

array([0, 2, 4, 6, 8])

In [35]:
# fancing indexing - 길이의 제한없음
data = np.array([1,2,3,4,5,6,7,8,9])
idx = np.array([0,2,4,6,8]) # 인덱스의 번지를 의미
data[idx]

array([1, 3, 5, 7, 9])

In [36]:
idx = np.array([0,0,0,1,1,1,2,2,2])
data[idx]

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [37]:
n_dim_ary = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
aryInfo(n_dim_ary)

type : <class 'numpy.ndarray'>
shape : (3, 4), dimension : 2, dtype : int32
Array's Data : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [38]:
# 첫번째와 네번째 열만 출력
n_dim_ary[:,[0,3]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [39]:
# boolean indexing
n_dim_ary[:,[True,False,False,True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [40]:
# 순서 다르게 출력
n_dim_ary[[2,0,1],:]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [41]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
aryInfo(x)

type : <class 'numpy.ndarray'>
shape : (20,), dimension : 1, dtype : int32
Array's Data : 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [42]:
# 3의 배수 찾기
print(x[x % 3 == 0])
# 4로 나누었을 때 나머지가 1인 수 찾기
print(x[x % 4 == 1])
# 3으로 나누면 나누어지고 4로 나누면 나머지가 1인 수 찾기
print(x[(x % 3 == 0) & (x % 4 == 1)],type(x[(x % 3 == 0) & (x % 4 == 1)]))

[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9] <class 'numpy.ndarray'>


### 배열의 생성과 변형

In [132]:
ary = np.arange(0,12,1)
aryInfo(ary)
# reshape : 배열의 크기 변형
ary = np.arange(0,12,1).reshape(3,4)
aryInfo(ary)

type : <class 'numpy.ndarray'>
shape : (12,), dimension : 1, dtype : int32
Array's Data : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
type : <class 'numpy.ndarray'>
shape : (3, 4), dimension : 2, dtype : int32
Array's Data : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [44]:
print(ary[2,2],type(ary[2,2]))
print(ary[1,2],type(ary[1,2]))
print(ary[1:2,2],type(ary[1:2,2]))
print(ary[1:2,1:2],type(ary[1,2:1:2]))
print(ary[:,[0,2]],type(ary[:,[0,2]]))

10 <class 'numpy.int32'>
6 <class 'numpy.int32'>
[6] <class 'numpy.ndarray'>
[[5]] <class 'numpy.ndarray'>
[[ 0  2]
 [ 4  6]
 [ 8 10]] <class 'numpy.ndarray'>


- Vector(1차원 - 배열) - pandas(Series)
- Matrix(N차원 - 행렬) - pandas(DataFrame)

In [45]:
aryInfo(ary[[0,2],2]) # 벡터
aryInfo(ary[[0,2],2:3]) # 행렬

type : <class 'numpy.ndarray'>
shape : (2,), dimension : 1, dtype : int32
Array's Data : 
 [ 2 10]
type : <class 'numpy.ndarray'>
shape : (2, 1), dimension : 2, dtype : int32
Array's Data : 
 [[ 2]
 [10]]


In [46]:
# 인덱스를 기준으로 찾기
# np.ix_()
aryInfo(ary[[0,2],[0,2]])
print('np.ix_()--->')
aryInfo(ary[np.ix_([0,2],[0,2])])
print('*'*50)
rowidx = np.array([0,2])
colidx = np.array([0,2])
aryInfo(ary[[rowidx]] [:,colidx])

type : <class 'numpy.ndarray'>
shape : (2,), dimension : 1, dtype : int32
Array's Data : 
 [ 0 10]
np.ix_()--->
type : <class 'numpy.ndarray'>
shape : (2, 2), dimension : 2, dtype : int32
Array's Data : 
 [[ 0  2]
 [ 8 10]]
**************************************************
type : <class 'numpy.ndarray'>
shape : (2, 2), dimension : 2, dtype : int32
Array's Data : 
 [[ 0  2]
 [ 8 10]]


<ipython-input-46-46cf51f3cb59>:9: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  aryInfo(ary[[rowidx]] [:,colidx])


In [47]:
x = np.array([1,2,3],dtype='f')
aryInfo(x)

type : <class 'numpy.ndarray'>
shape : (3,), dimension : 1, dtype : float32
Array's Data : 
 [1. 2. 3.]


- inf(np.innf(infinity))
- NaN(np.nan(not a number))

In [48]:
np.array([0,1,-1,0]) / np.array([1,0,0,0])

<ipython-input-48-720e9e2d83ea>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.array([0,1,-1,0]) / np.array([1,0,0,0])
<ipython-input-48-720e9e2d83ea>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array([0,1,-1,0]) / np.array([1,0,0,0])


array([  0.,  inf, -inf,  nan])

In [49]:
print(np.log(0))
print(np.exp(-np.inf))

-inf
0.0


<ipython-input-49-0d5d201f1928>:1: RuntimeWarning: divide by zero encountered in log
  print(np.log(0))


### 배열 생성 시 사용할 수 있는 함수
- array()
- arange()
- zeros(), ones()
- zeros_like(), ones_like()
- empty()
- linspace()

In [50]:
z = np.zeros(5)
aryInfo(z)

type : <class 'numpy.ndarray'>
shape : (5,), dimension : 1, dtype : float64
Array's Data : 
 [0. 0. 0. 0. 0.]


In [51]:
z = np.zeros((2,3))
aryInfo(z)

type : <class 'numpy.ndarray'>
shape : (2, 3), dimension : 2, dtype : float64
Array's Data : 
 [[0. 0. 0.]
 [0. 0. 0.]]


In [52]:
z = np.zeros((5,2),dtype='i')
aryInfo(z)

type : <class 'numpy.ndarray'>
shape : (5, 2), dimension : 2, dtype : int32
Array's Data : 
 [[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [53]:
o = np.ones((2,3,4),dtype='i')
aryInfo(o)

type : <class 'numpy.ndarray'>
shape : (2, 3, 4), dimension : 3, dtype : int32
Array's Data : 
 [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [54]:
# 크기를 튜플로 명시하지 않고 다른 배열과 같은 크기의 배열을 생성할 때
zl = np.zeros_like(z,dtype='f')
aryInfo(zl)

type : <class 'numpy.ndarray'>
shape : (5, 2), dimension : 2, dtype : float32
Array's Data : 
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [55]:
zl = np.ones_like(z,dtype='f')
aryInfo(zl)

type : <class 'numpy.ndarray'>
shape : (5, 2), dimension : 2, dtype : float32
Array's Data : 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [56]:
# 배열 생성 시 초기화를 단축시켜줌
e = np.empty((4,3))
aryInfo(e)

type : <class 'numpy.ndarray'>
shape : (4, 3), dimension : 2, dtype : float64
Array's Data : 
 [[1.05254544e-311 3.16202013e-322 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 1.53378774e-075]
 [2.69809345e+184 2.35909070e+184 2.65140325e-032]
 [2.65764230e+179 4.32177771e-061 6.57794788e-038]]


In [57]:
# 0 부터 n-1까지의 값 생성
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
# 시작, 끝(포함하지 않음), 단계
np.arange(3,21,2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [59]:
# 구간 나누기
# 시작, 끝(포함), 개수
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

- 전치행렬(transpose matrix) : 행렬의 행은 열로, 열은 행으로 바꾼 행렬
- T(속성)

In [135]:
ary = np.array([[1,2,3],[4,5,6]])
aryInfo(ary)

type : <class 'numpy.ndarray'>
shape : (2, 3), dimension : 2, dtype : int32
Array's Data : 
 [[1 2 3]
 [4 5 6]]


In [136]:
ary_t = ary.T
aryInfo(ary_t)

type : <class 'numpy.ndarray'>
shape : (3, 2), dimension : 2, dtype : int32
Array's Data : 
 [[1 4]
 [2 5]
 [3 6]]


In [137]:
# vector 에 transpose 가능할까?
vec = np.arange(10)
aryInfo(vec)
print('*'*50)
vec_t = vec.T
aryInfo(vec_t)
print('*'*50)
vec_r_t = vec.reshape(1,10).T
aryInfo(vec_r_t)

type : <class 'numpy.ndarray'>
shape : (10,), dimension : 1, dtype : int32
Array's Data : 
 [0 1 2 3 4 5 6 7 8 9]
**************************************************
type : <class 'numpy.ndarray'>
shape : (10,), dimension : 1, dtype : int32
Array's Data : 
 [0 1 2 3 4 5 6 7 8 9]
**************************************************
type : <class 'numpy.ndarray'>
shape : (10, 1), dimension : 2, dtype : int32
Array's Data : 
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [141]:
x = np.arange(12)
aryInfo(x)

type : <class 'numpy.ndarray'>
shape : (12,), dimension : 1, dtype : int32
Array's Data : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [66]:
xx = x.reshape(3,4)
aryInfo(xx)

type : <class 'numpy.ndarray'>
shape : (3, 4), dimension : 2, dtype : int32
Array's Data : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [67]:
# -1로 지정할 경우 열의 개수 자동으로 결정
x_reshape = x.reshape(3,-1)
aryInfo(x_reshape)

type : <class 'numpy.ndarray'>
shape : (3, 4), dimension : 2, dtype : int32
Array's Data : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [68]:
x_reshape = x.reshape(2,2,-1)
aryInfo(x_reshape)

type : <class 'numpy.ndarray'>
shape : (2, 2, 3), dimension : 3, dtype : int32
Array's Data : 
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [69]:
# 열을 기준으로 행의 개수 자동으로 결정
x_reshape = x.reshape(2,-1,2)
aryInfo(x_reshape)

type : <class 'numpy.ndarray'>
shape : (2, 3, 2), dimension : 3, dtype : int32
Array's Data : 
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


- 행렬을 벡터로 변형한다면 (flatten())
- 다차원 배열 -> 1차원 배열

In [71]:
aryInfo(x_reshape.flatten())

type : <class 'numpy.ndarray'>
shape : (12,), dimension : 1, dtype : int32
Array's Data : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [77]:
# reshape(변경) 시 주의
# 출력결과는 동일하지만 형태는 다름
# 1차원 vs 다차원
x = np.arange(5)
aryInfo(x)

type : <class 'numpy.ndarray'>
shape : (5,), dimension : 1, dtype : int32
Array's Data : 
 [0 1 2 3 4]


In [78]:
x_re = x.reshape(1,5)
aryInfo(x_re)

type : <class 'numpy.ndarray'>
shape : (1, 5), dimension : 2, dtype : int32
Array's Data : 
 [[0 1 2 3 4]]


In [76]:
x_re = x.reshape(5,1)
aryInfo(x_re)

type : <class 'numpy.ndarray'>
shape : (5, 1), dimension : 2, dtype : int32
Array's Data : 
 [[0]
 [1]
 [2]
 [3]
 [4]]


### 1차원 혹은 2차원 데이터에 대한 roop 작업가능
- ndarray iterator - nditer()
- 공부 필요!

In [79]:
for tmp in x :
    print(tmp,end=" ")

0 1 2 3 4 

In [142]:
# c_index : 1차원 배열에 대한 nditer()
ite = np.nditer(x, flags=['c_index'])
while not ite.finished :
    print(x[ite.index],end=" ")
    ite.iternext()

0 1 2 3 4 5 6 7 8 9 10 11 

In [143]:
# 2차원 배열에 대한 순차접근
two_dim_ary = np.array([[1,2,3],[4,5,6]])
aryInfo(two_dim_ary)

type : <class 'numpy.ndarray'>
shape : (2, 3), dimension : 2, dtype : int32
Array's Data : 
 [[1 2 3]
 [4 5 6]]


In [154]:
# 2차원 배열에 대한 순차적 접근
# 2행 3열
print(two_dim_ary.shape[0],type(two_dim_ary.shape[0])) # row
print(two_dim_ary.shape[1]) # col

for i in range(two_dim_ary.shape[0]) :
    for j in range(two_dim_ary.shape[1]) :
        print(two_dim_ary[i][j],end=" ")
    print('\n')

2 <class 'int'>
3
1 2 3 

4 5 6 



In [155]:
# c_index : 2차원 배열에 대한 nditer()
ite = np.nditer(two_dim_ary, flags=['multi_index'])
while not ite.finished :
    print(two_dim_ary[ite.multi_index],end="\n")
    ite.iternext()

1
2
3
4
5
6
