In [1]:
import numpy as np

### [실습 01]

In [2]:
data = np.loadtxt('./data/ratings.dat' , delimiter = "::", dtype=np.int64)

In [3]:
def aryInfo(arr) :
    print('type : {}'.format(type(arr)))
    print('shape : {}, dimension : {}, dtype : {}'.format(arr.shape, arr.ndim, arr.dtype))
    print("Array's Data : \n", arr)

In [4]:
data[:5,:]

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291]], dtype=int64)

In [5]:
aryInfo(data)

type : <class 'numpy.ndarray'>
shape : (1000209, 4), dimension : 2, dtype : int64
Array's Data : 
 [[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 ...
 [     6040       562         5 956704746]
 [     6040      1096         4 956715648]
 [     6040      1097         4 956715569]]


In [6]:
data[:,2].mean()

3.581564453029317

In [7]:
user_ids = np.unique(data[:,0])
print(user_ids)

[   1    2    3 ... 6038 6039 6040]


In [13]:
data_list = []
for user_id in user_ids :
    user = data[data[:,0]==user_id,:]
    user_rating = user[:,2].mean()
    data_list.append([user_id,user_rating])    

In [21]:
user_rating = np.array(data_list) 
aryInfo(user_rating)

type : <class 'numpy.ndarray'>
shape : (6040, 2), dimension : 2, dtype : float64
Array's Data : 
 [[1.00000000e+00 4.18867925e+00]
 [2.00000000e+00 3.71317829e+00]
 [3.00000000e+00 3.90196078e+00]
 ...
 [6.03800000e+03 3.80000000e+00]
 [6.03900000e+03 3.87804878e+00]
 [6.04000000e+03 3.57771261e+00]]


In [23]:
high_rating = user_rating[user_rating[:,1]>=4]
aryInfo(high_rating)

type : <class 'numpy.ndarray'>
shape : (1544, 2), dimension : 2, dtype : float64
Array's Data : 
 [[1.00000000e+00 4.18867925e+00]
 [4.00000000e+00 4.19047619e+00]
 [7.00000000e+00 4.32258065e+00]
 ...
 [6.02700000e+03 4.25000000e+00]
 [6.03200000e+03 4.13461538e+00]
 [6.03400000e+03 4.09523810e+00]]


In [26]:
np.savetxt('high_rating.csv',high_rating,fmt='%.1f',delimiter=',')

### [실습 02]

In [159]:
seoul_data = np.loadtxt('./data/seoul.csv',delimiter=',',dtype=np.object,skiprows=1)
aryInfo(seoul_data)
daegu_data = np.loadtxt('./data/daegu.csv',delimiter=',',dtype=np.object,skiprows=1)
aryInfo(daegu_data)

type : <class 'numpy.ndarray'>
shape : (40819, 5), dimension : 2, dtype : object
Array's Data : 
 [['1907-10-01' '108' '13.5' '7.9' '20.7']
 ['1907-10-02' '108' '16.2' '7.9' '22']
 ['1907-10-03' '108' '16.2' '13.1' '21.3']
 ...
 ['2020-09-04' '108' '23.3' '19.9' '27.5']
 ['2020-09-05' '108' '23.3' '19.2' '27.3']
 ['2020-09-06' '108' '21.7' '19.5' '24.4']]
type : <class 'numpy.ndarray'>
shape : (41493, 5), dimension : 2, dtype : object
Array's Data : 
 [['1907-01-31' '143' '' '-7' '0.8']
 ['1907-02-01' '143' '' '' '']
 ['1907-02-02' '143' '' '' '']
 ...
 ['2020-09-04' '143' '24.1' '18.3' '30.4']
 ['2020-09-05' '143' '19.9' '17.3' '23.1']
 ['2020-09-06' '143' '19.5' '17.6' '20.7']]


In [182]:
high_temp_seoul = seoul_data[:,4]
aryInfo(high_temp_seoul)
# 객체 타입 '' (결측값 의미) -> 결측값 제거 후 실수형 변환
high_temp = high_temp_seoul[high_temp_seoul!=''].astype(np.float64)
aryInfo(high_temp)
high_temp_max = high_temp.max()
# print(high_temp_max)
high_temp_date = seoul_data[:,0][high_temp_seoul==str(high_temp_max)]
# print(high_temp_date,type(high_temp_date))
print('서울 최고 기온 : {}, 기온이 가장 높았던 날 : {}'.format(high_temp_max,high_temp_date))

type : <class 'numpy.ndarray'>
shape : (40819,), dimension : 1, dtype : object
Array's Data : 
 ['20.7' '22' '21.3' ... '27.5' '27.3' '24.4']
type : <class 'numpy.ndarray'>
shape : (40061,), dimension : 1, dtype : float64
Array's Data : 
 [20.7 22.  21.3 ... 27.5 27.3 24.4]
서울 최고 기온 : 39.6, 기온이 가장 높았던 날 : ['2018-08-01']


In [185]:
low_temp_seoul = seoul_data[:,3]
aryInfo(low_temp_seoul)
# 객체 타입 -> 실수형 변환
# 의문) 행의 개수가 다르게 출력되는 이유?
# low_temp = low_temp_seoul[low_temp_seoul!=''].astype(np.float64)
# aryInfo(low_temp)

type : <class 'numpy.ndarray'>
shape : (40819,), dimension : 1, dtype : object
Array's Data : 
 ['7.9' '7.9' '13.1' ... '19.9' '19.2' '19.5']


In [189]:
# 결측값 처리
a = 0
for i in range(seoul_data.shape[0]) :
    for j in range(seoul_data.shape[1]) :
        if seoul_data[i][j] == '':
            seoul_data[i][j] = np.nan
            a +=1
print(a)

0


In [192]:
seoul_temp = seoul_data[:,2:].astype(np.float)
aryInfo(seoul_temp)

type : <class 'numpy.ndarray'>
shape : (40819, 3), dimension : 2, dtype : float64
Array's Data : 
 [[13.5  7.9 20.7]
 [16.2  7.9 22. ]
 [16.2 13.1 21.3]
 ...
 [23.3 19.9 27.5]
 [23.3 19.2 27.3]
 [21.7 19.5 24.4]]


In [193]:
temp = np.hstack([seoul_data,seoul_temp])
aryInfo(temp)

type : <class 'numpy.ndarray'>
shape : (40819, 8), dimension : 2, dtype : object
Array's Data : 
 [['1907-10-01' '108' '13.5' ... 13.5 7.9 20.7]
 ['1907-10-02' '108' '16.2' ... 16.2 7.9 22.0]
 ['1907-10-03' '108' '16.2' ... 16.2 13.1 21.3]
 ...
 ['2020-09-04' '108' '23.3' ... 23.3 19.9 27.5]
 ['2020-09-05' '108' '23.3' ... 23.3 19.2 27.3]
 ['2020-09-06' '108' '21.7' ... 21.7 19.5 24.4]]


In [216]:
diff_temp = seoul_data[(temp[:,-1] - temp[:,-2,]).argmax()]
print(diff_temp[0])

1942-04-19


In [256]:
date = np.array(seoul_data[:,0], dtype='datetime64[M]')
aryInfo(date)

type : <class 'numpy.ndarray'>
shape : (40819,), dimension : 1, dtype : datetime64[M]
Array's Data : 
 ['1907-10' '1907-10' '1907-10' ... '2020-09' '2020-09' '2020-09']
