### 배열의 확장
- hstack : 수평으로 행렬 합치기
- vstack : 수직으로 행렬 합치기
- dstack
- r_ : [] 사용 
- c_ : [] 사용
- tile

In [2]:
import numpy as np

In [3]:
def aryInfo(arr) :
    print('type : {}'.format(type(arr)))
    print('shape : {}, dimension : {}, dtype : {}'.format(arr.shape, arr.ndim, arr.dtype))
    print("Array's Data : \n", arr)

In [200]:
# hstack : 열변환 / 행의 숫자 동일해야함
h_ary_01 = np.ones((2,3))
aryInfo(h_ary_01)

type : <class 'numpy.ndarray'>
shape : (2, 3), dimension : 2, dtype : float64
Array's Data : 
 [[1. 1. 1.]
 [1. 1. 1.]]


In [201]:
# astype() : 타입변환
re_type = h_ary_01.astype(np.int32)
aryInfo(re_type)

type : <class 'numpy.ndarray'>
shape : (2, 3), dimension : 2, dtype : int32
Array's Data : 
 [[1 1 1]
 [1 1 1]]


In [202]:
# hstack
h_ary_02 = np.zeros((2,3))
aryInfo(h_ary_02)

type : <class 'numpy.ndarray'>
shape : (2, 3), dimension : 2, dtype : float64
Array's Data : 
 [[0. 0. 0.]
 [0. 0. 0.]]


In [205]:
# hstack : 행의 수가 같은 두 개 이상의 배열을 옆으로 연결
h_1 = np.hstack([h_ary_01,h_ary_02])
aryInfo(h_1)

type : <class 'numpy.ndarray'>
shape : (2, 6), dimension : 2, dtype : float64
Array's Data : 
 [[1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]]


In [207]:
# vstack : 열의 수가 같은 두 개 이상의 배열을 위아래로 연결
h_2 = np.vstack([h_ary_01,h_ary_02])
aryInfo(h_2)

type : <class 'numpy.ndarray'>
shape : (4, 3), dimension : 2, dtype : float64
Array's Data : 
 [[1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [209]:
# 의문
# dstack : 깊이 / 행
d_ary_01 = np.ones((3,4))
aryInfo(d_ary_01)
d_ary_02 = np.zeros((3,4))
aryInfo(d_ary_02)

type : <class 'numpy.ndarray'>
shape : (3, 4), dimension : 2, dtype : float64
Array's Data : 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
type : <class 'numpy.ndarray'>
shape : (3, 4), dimension : 2, dtype : float64
Array's Data : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [208]:
# shape에 대한 변화 / 행과 열이 바뀜
# (3 * 4) -> (3 * 4 * 2)
d_12 = np.dstack([d_ary_01, d_ary_02])
aryInfo(d_12)

type : <class 'numpy.ndarray'>
shape : (3, 4, 2), dimension : 3, dtype : float64
Array's Data : 
 [[[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]]


In [26]:
# 헷갈림
# stack : 기본병합 / 배열의 크기 동일해야함
# axis 설정 시 행에 대한 결합이 이루어짐 / defalut = 0
# (3 * 4) -> (3 * 2 * 4)
s_ary = np.stack([d_ary_01,d_ary_02],axis=1)
aryInfo(s_ary)

type : <class 'numpy.ndarray'>
shape : (3, 2, 4), dimension : 3, dtype : float64
Array's Data : 
 [[[1. 1. 1. 1.]
  [0. 0. 0. 0.]]

 [[1. 1. 1. 1.]
  [0. 0. 0. 0.]]

 [[1. 1. 1. 1.]
  [0. 0. 0. 0.]]]


In [27]:
# 벡터에 대한 결합 시 indexer 사용하는 것이 좋음
#row bind
np.r_[np.array([1,2,3]),np.array([4,5,6])]

array([1, 2, 3, 4, 5, 6])

In [28]:
# col bind
np.c_[np.array([1,2,3]),np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [29]:
np.r_[d_ary_01,d_ary_02]

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
np.c_[d_ary_01,d_ary_02]

array([[1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.]])

- tile : 동일한 배열 반복하여 연결

In [31]:
t_ary = np.array([[1,2,3],[4,5,6]])
aryInfo(t_ary)

type : <class 'numpy.ndarray'>
shape : (2, 3), dimension : 2, dtype : int32
Array's Data : 
 [[1 2 3]
 [4 5 6]]


In [32]:
# 2는 반복의 횟수를 의미함
np.tile(t_ary,2)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [34]:
# 튜플 형식으로 행과 열에 대한 추가 
np.tile(t_ary,(3,2))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [55]:
x = np.zeros((3,3))
# aryInfo(x)
y = np.ones((3,2))
# aryInfo(zy)
xy = np.hstack([x,y])
# aryInfo(xy)
z = np.arange(10,160,10).reshape((3,5))
# aryInfo(z)
xyz = np.vstack([xy,z])
answer = np.tile(xyz,(2,1))
aryInfo(answer)

type : <class 'numpy.ndarray'>
shape : (12, 5), dimension : 2, dtype : float64
Array's Data : 
 [[  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]
 [110. 120. 130. 140. 150.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]
 [110. 120. 130. 140. 150.]]


### delete()
- 행과 열 삭제 : axis
- row data는 변경하지 않고 새로운 배열 리턴
- ex) null, NaN, inf ,,

In [57]:
ary = np.random.randint(0,10,(3,4))
aryInfo(ary)

type : <class 'numpy.ndarray'>
shape : (3, 4), dimension : 2, dtype : int32
Array's Data : 
 [[2 4 3 6]
 [1 0 5 9]
 [7 2 7 1]]


In [60]:
# axis = 0 : 행을 기준으로 1번째 행 삭제
# np.delete(ary, 기준 인덱스, 기준 축)
result = np.delete(ary,1,axis=0)
aryInfo(result)
# axis 지정 안할 시 인덱스에 해당하는 값 삭제
result = np.delete(ary,0)
aryInfo(result)

type : <class 'numpy.ndarray'>
shape : (2, 4), dimension : 2, dtype : int32
Array's Data : 
 [[2 4 3 6]
 [7 2 7 1]]
type : <class 'numpy.ndarray'>
shape : (11,), dimension : 1, dtype : int32
Array's Data : 
 [4 3 6 1 0 5 9 7 2 7 1]


### loadtxt()

In [94]:
# np.object : 수치형->문자열로 받아오기
row_data = np.loadtxt('./data/crime_in_Seoul.csv',delimiter='\,',dtype=np.object,skiprows=1)
# 1차원의 배열 / '' 한 줄의 데이터가 문자열로 출력
aryInfo(row_data) 

type : <class 'numpy.ndarray'>
shape : (31,), dimension : 1, dtype : object
Array's Data : 
 ['중부서,2,2,3,2,105,65,"1,395",477,"1,355","1,170"'
 '종로서,3,3,6,5,115,98,"1,070",413,"1,278","1,070"'
 '남대문서,1,0,6,4,65,46,"1,153",382,869,794'
 '서대문서,2,2,5,4,154,124,"1,812",738,"2,056","1,711"'
 '혜화서,3,2,5,4,96,63,"1,114",424,"1,015",861'
 '용산서,5,5,14,14,194,173,"1,557",587,"2,050","1,704"'
 '성북서,2,2,2,1,86,71,953,409,"1,194","1,015"'
 '동대문서,5,5,13,13,173,146,"1,981",814,"2,548","2,227"'
 '마포서,8,8,14,10,294,247,"2,555",813,"2,983","2,519"'
 '영등포서,14,12,22,20,295,183,"2,964",978,"3,572","2,961"'
 '성동서,4,4,9,8,126,119,"1,607",597,"1,612","1,395"'
 '동작서,5,5,9,5,285,139,"1,865",661,"1,910","1,587"'
 '광진서,4,4,14,26,240,220,"3,026","1,277","2,625","2,180"'
 '서부서,2,2,2,1,70,59,819,293,"1,192","1,038"'
 '강북서,7,8,14,13,153,126,"1,434",618,"2,649","2,348"'
 '금천서,3,4,6,6,151,122,"1,567",888,"2,054","1,776"'
 '중랑서,13,12,11,9,187,148,"2,135",829,"2,847","2,407"'
 '강남서,3,3,15,12,300,225,"2,411",984,"2,465","

### 벡터(1차원배열) 연산

In [213]:
x = np.arange(1,10001)
y = np.arange(10001,20001)

- %%time : 실행속도 확인함수

In [216]:
%%time
z = np.zeros_like(x)
for i in range(10000) :
    z[i] = x[i] + y[i]

Wall time: 12 ms


In [217]:
%%time
z = x + y

Wall time: 0 ns


In [86]:
a = np.array([1,2,3,4])
b = np.array([5,2,6,4])
c = np.array([1,2,3,4])
print(a == b)
print(a >= b)

[False  True False  True]
[False  True False  True]


In [87]:
# a와 b의 값이 모두 동일한가?
np.all(a == b)

False

In [88]:
np.all(a == c)

True

In [89]:
# 벡터에 대하여 스칼라 연산 가능
a * 10

array([10, 20, 30, 40])

In [90]:
x = np.arange(12).reshape(3,4)
print(x * 100)

[[   0  100  200  300]
 [ 400  500  600  700]
 [ 800  900 1000 1100]]


- 벡터나 행렬의 연산 시 크기가 같아야함
- 브로드캐스팅 : 크기가 달라도 가능 / 크기가 작은 배열 -> 큰 배열에 맞춤

In [218]:
x = np.arange(5)
print(x)

[0 1 2 3 4]


In [219]:
y = np.ones_like(x)
print(y)

[1 1 1 1 1]


In [220]:
x + y 

array([1, 2, 3, 4, 5])

In [221]:
x + 1

array([1, 2, 3, 4, 5])

In [222]:
x = np.arange(5).reshape(5,1)
# print(x)
y = np.arange(1,6).reshape(5,1)
# print(y)
z = np.arange(2,7).reshape(5,1)
# print(z)
xyz = np.hstack([x,y,z])
print(xyz)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


In [227]:
# 이해안됨
# 동일한 결과 다른 방법
x = np.vstack([range(7)[i:i+3] for i in range(5)])
print(x)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


In [231]:
# 1차원의 벡터
y = np.arange(5)
aryInfo(y)

type : <class 'numpy.ndarray'>
shape : (5,), dimension : 1, dtype : int32
Array's Data : 
 [0 1 2 3 4]


In [236]:
# 1차원 -> 2차원으로 변경
# 길이가 1인 배열 추가
y = np.arange(5)[:,np.newaxis]
aryInfo(y)
y1 = np.arange(5)[np.newaxis,:]
aryInfo(y1)

type : <class 'numpy.ndarray'>
shape : (5, 1), dimension : 2, dtype : int32
Array's Data : 
 [[0]
 [1]
 [2]
 [3]
 [4]]
type : <class 'numpy.ndarray'>
shape : (1, 5), dimension : 2, dtype : int32
Array's Data : 
 [[0 1 2 3 4]]


In [237]:
x + y

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [238]:
y = np.arange(3)
y

array([0, 1, 2])

In [239]:
x + y

array([[0, 2, 4],
       [1, 3, 5],
       [2, 4, 6],
       [3, 5, 7],
       [4, 6, 8]])

- 차원축소

In [240]:
x = np.array([1,2,3,4])
aryInfo(x)

type : <class 'numpy.ndarray'>
shape : (4,), dimension : 1, dtype : int32
Array's Data : 
 [1 2 3 4]


In [241]:
aryInfo(np.sum(x))

type : <class 'numpy.int32'>
shape : (), dimension : 0, dtype : int32
Array's Data : 
 10


In [242]:
aryInfo(x.sum())

type : <class 'numpy.int32'>
shape : (), dimension : 0, dtype : int32
Array's Data : 
 10


In [243]:
print(x.min())
print(x.max())

1
4


In [126]:
# 최솟값의 위치 index return 
print(x.argmin())
# 최댓값의 위치 index return 
print(x.argmax())

0
3


In [127]:
x.mean()

2.5

In [128]:
x = np.array([[1,2,3,4],[5,6,7,8]])
aryInfo(x)

type : <class 'numpy.ndarray'>
shape : (2, 4), dimension : 2, dtype : int32
Array's Data : 
 [[1 2 3 4]
 [5 6 7 8]]


In [132]:
# 기준 축 지정하지 않을경우 행렬에 대한 모든 합 계산
print(x.sum())
# 기준 축 지정 - 열에 대한 연산
aryInfo(x.sum(axis=0))
# 행에 대한 연산
aryInfo(x.sum(axis=1))

36
type : <class 'numpy.ndarray'>
shape : (4,), dimension : 1, dtype : int32
Array's Data : 
 [ 6  8 10 12]
type : <class 'numpy.ndarray'>
shape : (2,), dimension : 1, dtype : int32
Array's Data : 
 [10 26]


실수로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구한다.

- 전체의 최댓값
- 각 행의 합
- 각 행의 최댓값
- 각 열의 평균
- 각 열의 최솟값


In [137]:
a = np.random.randint(0,10,(5,6))
aryInfo(a)

type : <class 'numpy.ndarray'>
shape : (5, 6), dimension : 2, dtype : int32
Array's Data : 
 [[3 0 5 3 6 2]
 [9 9 9 0 6 2]
 [0 0 1 4 1 6]
 [5 4 7 7 3 2]
 [3 6 0 5 3 6]]


In [143]:
print(a.max())
print(a.sum(axis=1))
print(a.max(axis=1))
print(a.mean(axis=0))
print(a.min(axis=0))

9
[19 35 12 28 23]
[6 9 6 7 6]
[4.  3.8 4.4 3.8 3.8 3.6]
[0 0 0 0 1 2]


- ndarray 정렬
- axis를 기준으로 정렬하는 sort()
- np.sort() : 새로운 정렬된 결과 반환 / 원본 데이터 변경x
- ary.sort() : Noen Return / 원본 데이터에 대한 정렬

In [144]:
ary = np.arange(10)
aryInfo(ary)

type : <class 'numpy.ndarray'>
shape : (10,), dimension : 1, dtype : int32
Array's Data : 
 [0 1 2 3 4 5 6 7 8 9]


In [150]:
np.random.shuffle(ary)
aryInfo(ary)

type : <class 'numpy.ndarray'>
shape : (10,), dimension : 1, dtype : int32
Array's Data : 
 [0 5 4 7 1 8 2 9 3 6]


In [154]:
# 리턴 존재하지않음
ary.sort()
print(ary)
# 리턴 존재함
ary_asc = np.sort(ary)
print(ary_asc)
# 내림차순
ary_desc = np.sort(ary)[::-1]
print(ary_desc)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


In [159]:
# 헷갈림
# 행렬에 대한 정렬
# axis = 0 : 열
# axis = 1 : 행
ary = np.random.randint(0,17,(4,4))
aryInfo(ary)
ary_asc = np.sort(ary,axis=0)
print(ary_asc)
ary_asc = np.sort(ary,axis=1)
print(ary_asc)

type : <class 'numpy.ndarray'>
shape : (4, 4), dimension : 2, dtype : int32
Array's Data : 
 [[ 9 10  4 13]
 [11  5 15 11]
 [ 3  6  4 15]
 [11  4 16 16]]
[[ 3  4  4 11]
 [ 9  5  4 13]
 [11  6 15 15]
 [11 10 16 16]]
[[ 4  9 10 13]
 [ 5 11 11 15]
 [ 3  4  6 15]
 [ 4 11 16 16]]


In [160]:
# inplace : 원본 데이터에 대한 변경
ary.sort(axis=1)
print(ary)

[[ 4  9 10 13]
 [ 5 11 11 15]
 [ 3  4  6 15]
 [ 4 11 16 16]]


- 만약, 정렬된 인덱스의 값을 필요로 한다면?
- np.argsort()

In [161]:
np.argsort(ary)

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]], dtype=int64)

다음 배열은 
첫번째 행(row)에 학번, 
두번째 행에 영어 성적, 
세번째 행에 수학 성적을 적은 배열이다. 

영어 성적을 기준으로 각 열(column)을 재정렬하라.

array([[  1,    2,    3,    4],
       [ 46,   99,  100,   71],
       [ 81,   59,   90,  100]])

In [193]:
x = np.array([[1,2,3,4],
              [46,99,100,71],
              [81,59,90,100]])
aryInfo(x)

# sort에 대한 문제점 발생
idx = np.argsort(x[1].argsort())
print(idx)

# 결과는 출력되는데 뭐가 문제일까?
idx = np.argsort(x)[1]
print(idx)
x[:,idx]
print(x[:,idx])

answer = x[:,x[1].argsort()]
aryInfo(answer)

type : <class 'numpy.ndarray'>
shape : (3, 4), dimension : 2, dtype : int32
Array's Data : 
 [[  1   2   3   4]
 [ 46  99 100  71]
 [ 81  59  90 100]]
[0 2 3 1]
[0 3 1 2]
[[  1   4   2   3]
 [ 46  71  99 100]
 [ 81 100  59  90]]
type : <class 'numpy.ndarray'>
shape : (3, 4), dimension : 2, dtype : int32
Array's Data : 
 [[  1   4   2   3]
 [ 46  71  99 100]
 [ 81 100  59  90]]


- row or cols 추가하는 방법

In [195]:
ary = np.array([[1,2,3],[4,5,6]])
aryInfo(ary)
new_row = np.array([7,8,9])
aryInfo(new_row)

type : <class 'numpy.ndarray'>
shape : (2, 3), dimension : 2, dtype : int32
Array's Data : 
 [[1 2 3]
 [4 5 6]]
type : <class 'numpy.ndarray'>
shape : (3,), dimension : 1, dtype : int32
Array's Data : 
 [7 8 9]


In [197]:
result = np.concatenate((ary,new_row.reshape(1,3)),axis=0)
aryInfo(result)

type : <class 'numpy.ndarray'>
shape : (3, 3), dimension : 2, dtype : int32
Array's Data : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [199]:
new_col = np.array([7,8,9,10])
result = np.concatenate((ary,new_col.reshape(2,2)),axis=1)
aryInfo(result)

type : <class 'numpy.ndarray'>
shape : (2, 5), dimension : 2, dtype : int32
Array's Data : 
 [[ 1  2  3  7  8]
 [ 4  5  6  9 10]]
